---
name: Luacheck
on:
  push:
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: '**.lua'

